# Echelon @build Codex 12/08/2026 Central public brand identity for fork-owned build and packaging layers.
set(ECHELON_PRODUCT_NAME "Echelon")
set(ECHELON_PRODUCT_SLUG "Echelon")
set(ECHELON_FLATPAK_ID "io.github.cheviiot.Echelon")
set(ECHELON_OUTPUT_DIRECTORY "Echelon")
set(ECHELON_INSTALL_DATA_DIRECTORY "share/echelon")
set(ECHELON_INSTALL_MODULE_DIRECTORY "lib/echelon")
set(ECHELON_DATA_DIRECTORY ".Echelon")
set(ECHELON_INSTALL_SLUG "echelon")
set(ECHELON_MODULE_EXPORT "Echelon_GetEngineModuleV2")
set(ECHELON_RELEASE_API_URL "https://api.github.com/repos/Cheviiot/Echelon/releases/latest")
set(ECHELON_RELEASES_URL "https://github.com/Cheviiot/Echelon/releases")
set(ECHELON_UPDATE_USER_AGENT "Echelon/update-checker")
set(ECHELON_RELEASE_TAG_PREFIX "Echelon-")
set(ECHELON_RELEASE_TAG_PREFIX_LOWER "echelon-")
set(ECHELON_PROJECT_WATERMARK "Echelon - Unified C&C Generals")
